#! .goreleaser.yaml
changelog:
  use: github

release:
  github:
    owner: unikraft
    name: kraftkit
  draft: false
  prerelease: false
  mode: replace
  header: |
    ## KraftKit {{ .Tag }} ({{ .Date }})

    This is a stable release of kraftkit.
  name_template: 'v{{ .Version }}'

nfpms:
  - vendor: Unikraft
    maintainer: Alexander Jung <alex@unikraft.io>
    description: Build and use highly customized and ultra-lightweight unikernels.
    license: BSD 3-clause
    bindir: /usr/local/bin
    homepage: https://kraftkit.sh
    formats:
      - deb
      - rpm
      - apk

aurs:
  - homepage: https://kraftkit.sh
    description: Build and use highly customized and ultra-lightweight unikernels
    maintainers:
      - "Alexander Jung <alex at unikraft dot io>"
    license: "BSD-3-Clause"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/kraftkit-bin.git"
    package: |-
      # bin
      install -Dm755 "${srcdir}/kraft" "${pkgdir}/usr/bin/kraft"
      # license
      install -Dm644 "${srcdir}/LICENSE.md" "${pkgdir}/usr/share/licenses/kraftkit/LICENSE"
    commit_author:
      name: Unikraft Bot
      email: monkey+aur@unikraft.io
nix:
  - name: kraftkit
    repository:
      owner: unikraft
      name: nur
    homepage: https://kraftkit.sh
    description: Build and use highly customized and ultra-lightweight unikernels
    path: pkgs/kraftkit/default.nix
    license: BSD-3-Clause
    install: |-
      mkdir -p $out/bin
      cp -vr ./dist/kraft $out/bin/kraft

builds:
#@ targets = {
#@   "linuxu": {"os": "linux", "arch": "amd64"},
#@   "darwin-arm64": {"os": "darwin", "arch": "arm64"},
#@   "darwin-amd64": {"os": "darwin", "arch": "amd64"}
#@ }
#@ for binary in ["kraft"]:
#@ for target, specs in targets.items():
  - id: #@ "{}-{}".format(binary, target)
    binary: #@ binary
    main: #@ "./cmd/{}".format(binary)
    env:
      - CGO_ENABLED=0
      - GOMOD=kraftkit.sh
    goos:
      - #@ specs["os"]
    goarch:
      - #@ specs["arch"]
    ldflags:
      - -s -w 
      - -X {{ .Env.GOMOD }}/internal/version.version={{ .Version }}
      - -X {{ .Env.GOMOD }}/internal/version.commit={{ .Commit }}
      - -X {{ .Env.GOMOD }}/internal/version.buildTime={{ .Date }}
#@ end
#@ end
